# try:
#     k=5//0
#     print(k)
# except ZeroDivisionError:
#     print("can not divided by zero")
# finally:
#     print("this is always execute")
#
# # Program to depict Raising Exception
#
# try:
# 	raise NameError("Hi there")
# except NameError:
# 	print ("An exception")
# 	raise

# try:
#     print("hii")
# except:
#     print("except occured")
#
#
# try:
#   print(x)
# except NameError:
#   print("Variable x is not defined")
# except:
#   print("Something else went wrong")
#
#
#
# try:
#   print("Hello")
# except:
#   print("Something went wrong")
# else:
#   print("Nothing went wrong")
#
#
# try:
#   print(x)
# except:
#   print("Something went wrong")
# finally:
#   print("The 'try except' is finished")
#
#
#
# try:
#   f = open("demofile.txt")
#   try:
#     f.write("Lorum Ipsum")
#   except:
#     print("Something went wrong when writing to the file")
#   finally:
#     f.close()
# except:
#   print("Something went wrong when opening the file")
#
# x = -1
# if x < 0:
#   raise Exception("Sorry, no numbers below zero")



